{ pkgs, config, hostvars, lib, ... }:

let
    masterWallpaperDir = "${config.home.homeDirectory}/Pictures/Wallpapers";
    defaultWallpaper = "${masterWallpaperDir}/makima.png";
in
{
    wayland.windowManager.hyprland = {
        enable = true;
        package = null; # installed as a systempkg, null here to prevent duplicate
        configType = "lua";

        extraConfig = ''
            hl.config({ autogenerated = false })

            hl.on("hyprland.shutdown", function()
                hl.exec_cmd("systemctl --user stop hyprland-session.target")
            end)

            hl.on("hyprland.start", function()
                hl.exec_cmd("${pkgs.dbus}/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
                hl.exec_cmd("sleep 3 && adb connect 192.168.3.113:5555")
                hl.exec_cmd("bash -c 'hyprctl dispatch submap nothing; while ! hyprctl layers -j | grep -q \"dms:bar\"; do sleep 0.1; done; sleep 0.5; hyprctl dispatch submap reset'")
                hl.exec_cmd("fcitx5 -d -r")
                hl.exec_cmd("${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1")
                hl.exec_cmd("sh -c 'sleep 3 && if ! grep -q \"wallpaperPath\" ~/.local/state/DankMaterialShell/session.json 2>/dev/null; then dms ipc wallpaper set ${defaultWallpaper}; fi'")
            end)

            hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
            hl.env("XDG_SESSION_TYPE", "wayland")
            hl.env("XDG_SESSION_DESKTOP", "Hyprland")
            hl.env("XMODIFIERS", "@im=fcitx")
            hl.env("QT_IM_MODULE", "fcitx")
            hl.env("SDL_IM_MODULE", "fcitx")

            local mainMod = "SUPER"
            local terminal = "kitty"

            hl.config({
                animations = {
                    enabled = true,
                },
                decoration = {
                    blur = {
                        enabled = true,
                        ignore_opacity = true,
                        passes = 3,
                        size = 4,
                    },
                },
                input = {
                    accel_profile = "flat",
                    kb_layout = "br",
                },
                misc = {
                    disable_hyprland_logo = true,
                    disable_splash_rendering = true,
                }
            })

            hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
            hl.animation({ leaf = "windows", enabled = true, speed = 3, bezier = "myBezier" })
            hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default", style = "popin 80%" })
            hl.animation({ leaf = "border", enabled = true, speed = 5, bezier = "default" })
            hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
            hl.animation({ leaf = "workspaces", enabled = true, speed = 1, bezier = "default" })

            hl.monitor({
                output = "",
                mode = "highrr",
                position = "auto",
                scale = "1",
            })

            hl.workspace_rule({ workspace = "1", monitor = "${hostvars.prMonitor}", default = true })
            hl.workspace_rule({ workspace = "2", monitor = "${hostvars.prMonitor}" })
            hl.workspace_rule({ workspace = "3", monitor = "${hostvars.prMonitor}" })
            hl.workspace_rule({ workspace = "4", monitor = "${hostvars.prMonitor}" })
            ${lib.optionalString (hostvars.seMonitor != "") "hl.workspace_rule({ workspace = \"5\", monitor = \"${hostvars.seMonitor}\", default = true })"}
            ${lib.optionalString (hostvars.thMonitor != "") "hl.workspace_rule({ workspace = \"6\", monitor = \"${hostvars.thMonitor}\", default = true })"}
            ${lib.optionalString (hostvars.foMonitor != "") "hl.workspace_rule({ workspace = \"7\", monitor = \"${hostvars.foMonitor}\", default = true })"}
            ${lib.optionalString (hostvars.fiMonitor != "") "hl.workspace_rule({ workspace = \"8\", monitor = \"${hostvars.fiMonitor}\", default = true })"}

            hl.bind(mainMod .. " + Pause", hl.dsp.exec_cmd("shutdown now"))
            hl.bind(mainMod .. " + F12", hl.dsp.submap("passthrough"))
            hl.bind(mainMod .. " + Apostrophe", hl.dsp.exec_cmd("gsr-notify --text \"$(hyprctl submap)\" --timeout 3 --bg-color FFFF00"))

            hl.bind("CONTROL + ALT + TAB", hl.dsp.window.close())
            hl.bind("CONTROL + ALT + TAB", hl.dsp.exec_cmd("dms ipc call bar reveal index 0"))
            hl.bind("CONTROL + SHIFT + Q", hl.dsp.exec_cmd(terminal))
            hl.bind("CONTROL + SHIFT + S", hl.dsp.exec_cmd("zen-beta"))
            hl.bind("CONTROL + SHIFT + D", hl.dsp.exec_cmd("kitty -e tmux new-session -A -s concord /etc/profiles/per-user/${config.home.username}/bin/concord"))
            hl.bind("CONTROL + SHIFT + 1", hl.dsp.exec_cmd("proton-pass"))
            hl.bind("CONTROL + SHIFT + 2", hl.dsp.exec_cmd("protonvpn-app"))
            hl.bind("CONTROL + SHIFT + A", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
            hl.bind("CONTROL + SHIFT + 3", hl.dsp.exec_cmd("dms ipc call settings toggle"))
            hl.bind("CONTROL + SHIFT + E", hl.dsp.exec_cmd("scrcpy --video-bit-rate=5M --max-fps=61 --max-size=720 --tcpip"))
            hl.bind(mainMod .. " + CONTROL + Alt_L", hl.dsp.exec_cmd("dms ipc call bar toggle index 0"))
            hl.bind("CONTROL + SHIFT + W", hl.dsp.exec_cmd("dms ipc wallpaperCarousel toggle"))
            hl.bind(mainMod .. " + 1", hl.dsp.exec_cmd("bruh - 10"))
            hl.bind(mainMod .. " + 2", hl.dsp.exec_cmd("bruh + 10"))
            hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("dms screenshot"))
            hl.bind("Print", hl.dsp.exec_cmd("dms screenshot full"))

            hl.bind(mainMod .. " + Shift_L", hl.dsp.focus({ direction = "left" }))
            hl.bind(mainMod .. " + X", hl.dsp.focus({ direction = "right" }))
            hl.bind(mainMod .. " + Z", hl.dsp.focus({ direction = "up" }))
            hl.bind(mainMod .. " + backslash", hl.dsp.focus({ direction = "down" }))

            hl.bind(mainMod .. " + Caps_Lock", hl.dsp.window.move({ direction = "l" }))
            hl.bind(mainMod .. " + D", hl.dsp.window.move({ direction = "r" }))
            hl.bind(mainMod .. " + S", hl.dsp.window.move({ direction = "u" }))
            hl.bind(mainMod .. " + A", hl.dsp.window.move({ direction = "d" }))

            hl.bind(mainMod .. " + CONTROL + Shift_L", hl.dsp.focus({ workspace = 1 }))
            hl.bind(mainMod .. " + CONTROL + backslash", hl.dsp.focus({ workspace = 2 }))
            hl.bind(mainMod .. " + CONTROL + Z", hl.dsp.focus({ workspace = 3 }))
            hl.bind(mainMod .. " + CONTROL + X", hl.dsp.focus({ workspace = 4 }))
            hl.bind(mainMod .. " + CONTROL + C", hl.dsp.focus({ workspace = 5 }))
            hl.bind(mainMod .. " + CONTROL + Caps_Lock", hl.dsp.focus({ workspace = 6 }))
            hl.bind(mainMod .. " + CONTROL + A", hl.dsp.focus({ workspace = 7 }))
            hl.bind(mainMod .. " + CONTROL + S", hl.dsp.focus({ workspace = 8 }))
            hl.bind(mainMod .. " + CONTROL + D", hl.dsp.focus({ workspace = 9 }))

            hl.bind("CONTROL + ALT + Shift_L", hl.dsp.window.move({ workspace = 1 }))
            hl.bind("CONTROL + ALT + backslash", hl.dsp.window.move({ workspace = 2 }))
            hl.bind("CONTROL + ALT + Z", hl.dsp.window.move({ workspace = 3 }))
            hl.bind("CONTROL + ALT + X", hl.dsp.window.move({ workspace = 4 }))
            hl.bind("CONTROL + ALT + C", hl.dsp.window.move({ workspace = 5 }))
            hl.bind("CONTROL + ALT + Caps_Lock", hl.dsp.window.move({ workspace = 6 }))
            hl.bind("CONTROL + ALT + A", hl.dsp.window.move({ workspace = 7 }))
            hl.bind("CONTROL + ALT + S", hl.dsp.window.move({ workspace = 8 }))
            hl.bind("CONTROL + ALT + D", hl.dsp.window.move({ workspace = 9 }))

            hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("killall -q wl-kbptr || wl-kbptr"))
            hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("wlrctl pointer click right"))
            hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("wlrctl pointer click left"))
            hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("wlrctl pointer click middle"))
            hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e+1" }))
            hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e-1" }))

            hl.bind("SHIFT + ALT + F9", hl.dsp.exec_cmd("gsr-toggle record nomic"))
            hl.bind("SHIFT + ALT + F10", hl.dsp.exec_cmd("gsr-toggle replay nomic"))
            hl.bind("SHIFT + ALT + F7", hl.dsp.exec_cmd("gsr-toggle record m"))
            hl.bind("SHIFT + ALT + F8", hl.dsp.exec_cmd("gsr-toggle replay m"))
            hl.bind("ALT + F10", hl.dsp.exec_cmd("gsr-toggle save"))

            hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
            hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
            hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 5%+"), { locked = true, repeating = true })
            hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 5%-"), { locked = true, repeating = true })

            hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
            hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
            hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
            hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
            hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

            hl.define_submap("passthrough", function()
                hl.bind(mainMod .. " + F12", hl.dsp.submap("reset"))

                hl.bind(mainMod .. " + Pause", hl.dsp.exec_cmd("shutdown now"))
                hl.bind(mainMod .. " + Apostrophe", hl.dsp.exec_cmd("gsr-notify --text \\\"$(hyprctl submap)\\\" --timeout 3 --bg-color FFFF00"))

                hl.bind(mainMod .. " + 1", hl.dsp.exec_cmd("bruh - 10"))
                hl.bind(mainMod .. " + 2", hl.dsp.exec_cmd("bruh + 10"))

                hl.bind(mainMod .. " + CONTROL + Alt_L", hl.dsp.exec_cmd("dms ipc call bar toggle index 0"))

                hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("dms screenshot"))
                hl.bind("Print", hl.dsp.exec_cmd("dms screenshot full"))

                hl.bind(mainMod .. " + CONTROL + Shift_L", hl.dsp.focus({ workspace = 1 }))
                hl.bind(mainMod .. " + CONTROL + backslash", hl.dsp.focus({ workspace = 2 }))
                hl.bind(mainMod .. " + CONTROL + Z", hl.dsp.focus({ workspace = 3 }))
                hl.bind(mainMod .. " + CONTROL + X", hl.dsp.focus({ workspace = 4 }))
                hl.bind(mainMod .. " + CONTROL + C", hl.dsp.focus({ workspace = 5 }))
                hl.bind(mainMod .. " + CONTROL + Caps_Lock", hl.dsp.focus({ workspace = 6 }))
                hl.bind(mainMod .. " + CONTROL + A", hl.dsp.focus({ workspace = 7 }))
                hl.bind(mainMod .. " + CONTROL + S", hl.dsp.focus({ workspace = 8 }))
                hl.bind(mainMod .. " + CONTROL + D", hl.dsp.focus({ workspace = 9 }))

                hl.bind(mainMod .. " + Shift_L", hl.dsp.focus({ direction = "left" }))
                hl.bind(mainMod .. " + X", hl.dsp.focus({ direction = "right" }))
                hl.bind(mainMod .. " + Z", hl.dsp.focus({ direction = "up" }))
                hl.bind(mainMod .. " + backslash", hl.dsp.focus({ direction = "down" }))

                hl.bind(mainMod .. " + Caps_Lock", hl.dsp.window.move({ direction = "l" }))
                hl.bind(mainMod .. " + D", hl.dsp.window.move({ direction = "r" }))
                hl.bind(mainMod .. " + S", hl.dsp.window.move({ direction = "u" }))
                hl.bind(mainMod .. " + A", hl.dsp.window.move({ direction = "d" }))

                hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
                hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
                hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 5%+"), { locked = true, repeating = true })
                hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 5%-"), { locked = true, repeating = true })
                hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
                hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
                hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
                hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
                hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

                hl.bind("SHIFT + ALT + F9", hl.dsp.exec_cmd("gsr-toggle record nomic"))
                hl.bind("SHIFT + ALT + F10", hl.dsp.exec_cmd("gsr-toggle replay nomic"))
                hl.bind("SHIFT + ALT + F7", hl.dsp.exec_cmd("gsr-toggle record m"))
                hl.bind("SHIFT + ALT + F8", hl.dsp.exec_cmd("gsr-toggle replay m"))
                hl.bind("ALT + F10", hl.dsp.exec_cmd("gsr-toggle save"))
            end)

            hl.define_submap("nothing", function()
                hl.bind("SUPER + SHIFT + ALT + CONTROL + F24", hl.dsp.exec_cmd("nothing"))
            end)

            -- Required DMS Rules
            -- Keep UI menus from animating weirdly
            hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
            hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

            -- === Core DMS Modules ===
            -- require("dms.colors")
            require("dms.outputs")
            --require("dms.layout")
            require("dms.cursor")
            --require("dms.binds")
            -- require("dms.binds-user")
            -- require("dms.windowrules")
        '';
    };
}
